[package]
name = "e-agent-basic-tools"
version = "0.1.0"
edition = "2024"

[lib]
name = "basic_tools"
crate-type = ["cdylib"]

[dependencies]
e-agent-tool = { path = "../../e-agent-tool" }
pyo3 = { version = "0.29.2", features = ["abi3-py314", "extension-module", "generate-import-lib"] }
schemars = "1.2.2"
serde = { version = "1.0.229", features = ["derive"] }
tokio = { version = "1.53.1", features = ["fs", "process", "time"] }
